#####
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Travis by default runs eg:
# install:
# - R -e 'devtools::install_deps(dep = T)'

# script:
# - R CMD build .
# - R CMD check *tar.gz

# and it looks like it already runs sessionInfo(), see:
# https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb
#####


language: R
sudo: false
cache: packages

# r_packages
# add dependencies here for testing, those in DESCRIPTION

jobs:
  include:
  - r: release
#  - os: osx
#  - r: devel
  - r: 3.4

r_packages:
-  dplyr
-  tibble
-  data.table
-  compare
-  stringi
-  stringr
-  lubridate
-  purrr
-  e1071
-  Hmisc
-  ggplot2
-  cowplot
# -  limma # not available in 3.5.1, only used for topTable in stats, add to DESCRIPTION when ready

r_binary_packages:
- testthat
- knitr

# Add coverage testing:
# https://covr.r-lib.org/
r_github_packages:
- r-lib/covr

after_success:
- Rscript -e 'covr::codecov()'


