#####
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Travis by default runs eg:
# install:
# - R -e 'devtools::install_deps(dep = T)'

# script:
# - R CMD build .
# - R CMD check *tar.gz

# and it looks like it already runs sessionInfo(), see:
# https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb
#####

language: R
sudo: false
cache: packages

matrix:
  fast_finish: true
  include:
  - name: "R release on Linux"
    r: release
    dist: trusty
    warnings_are_errors: false
    env:
      - VDIFFR_RUN_TESTS=false
      - _R_CHECK_SYSTEM_CLOCK_=false
  - name: "R devel on Linux"
    r: devel
    dist: trusty
    warnings_are_errors: false
    env:
      - VDIFFR_RUN_TESTS=false
      - _R_CHECK_SYSTEM_CLOCK_=false
  - name: "R 3.4 on Linux"
    r: 3.4
    dist: trusty
  - name: "R 3.5 on Linux"
    r: 3.5
    dist: trusty
  - name: "R 3.6 on Linux"
    r: 3.6
    dist: trusty    
  - name: "R 3.6 on macOS"
    r: 3.6
    os: osx
#   before_install:
#     - sudo tlmgr install framed titling
#   osx_image: xcode10.2
#   language: shell

r_packages:
    - dplyr
    - tibble
    - data.table
    - compare
    - stringi
    - stringr
    - lubridate
    - purrr
    - e1071
    - Hmisc
    - ggplot2
    - cowplot
    # -  limma # not available in 3.5.1, only used for topTable in stats, add to DESCRIPTION when ready
    - future
    - doFuture
    - foreach
    - iterators
    - parallel
    - tidyr
    - covr
    - vdiffr

r_binary_packages:
    - testthat
    - knitr

# Add coverage testing:
# https://covr.r-lib.org/
#r_github_packages:
#    - r-lib/covr

after_success:
    - Rscript -e 'library(covr); covr::codecov()'


