# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages


# Add coverage testing:
# https://covr.r-lib.org/
r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'

