#comment: false

codecov:
  token: ef11ac6f-e96c-4600-9f31-c1d6440674bd

coverage:
  status:
    project:
      default:
        target: auto
        threshold: null #1%
    patch:
      default:
        target: auto
        threshold: null #1%
