name: episcout
channels:
  - conda-forge
dependencies:
  - r-base
  - pandoc
  - qpdf
  - ghostscript
  - r-broom
  - r-compare
  - r-covr
  - r-cowplot
  - r-data.table
  - r-devtools
  - r-dofuture
  - r-dplyr
  - r-e1071
  - r-foreach
  - r-future
  - r-ggplot2
  - r-ggthemes
  - r-hmisc
  - r-iterators
  - r-knitr
  - r-lintr
  - r-lubridate
  - r-magrittr
  - r-mice
  - r-openxlsx
  - r-purrr
  - r-rcmdcheck
  - r-remotes
  - r-renv
  - r-reshape2
  - r-rlang
  - r-rmarkdown
  - r-roxygen2
  - r-scales
  - r-stringi
  - r-stringr
  - r-styler
  - r-survival
  - r-testthat
  - r-tibble
  - r-tidyr
  - r-usethis
  - r-vdiffr
  - r-withr
