# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# check:
# check-standard.yaml is likely a better choice.
# usethis::use_github_action("check-standard") will install it

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R CMD CHECK

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: ubuntu-latest,  r: 'release'}
#          - {os: ubuntu-latest,  r: 'devel', http-user-agent: 'release'}
#          - {os: ubuntu-latest,  r: 'oldrel-1'}
#          - {os: windows-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      # For file snapshot that uses png
      - name: Install xquartz
        if: runner.os == 'macOS'
        run: brew install --cask xquartz

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      #- uses: r-lib/actions/setup-r-dependencies@v2
      #  with:
      #    extra-packages: any::rcmdcheck
      #    needs: check

      - name: Install system dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::devtools
            any::roxygen2
            any::testthat
            any::covr
            any::lintr
            any::styler
          #  any::pkgdown
          needs: check

      - name: Install package dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      # Try to ensure Linux CI has the same fonts as macOS for svg plot tests
      # with vdiffr so that R CMD check on ubuntu match the macOS generated images
      #- name: Install system fonts
      #  run: |
      #    sudo apt-get update sudo: apt-get: command not found
      #    sudo apt-get install -y fonts-dejavu-core libfreetype6-dev

      - name: Run R CMD check
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
