# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

# Add the CRAN mirror environment variable globally to the job
#env:
#  CRAN: https://cloud.r-project.org
  
name: R-CMD-check

# Trigger on push and PR to main (rename branch as needed)
on:
  push:
    branches: [ master ]
    # Optional: build pkgdown on tag push
    tags: [ "v*" ]

  pull_request:
    branches: [ master ]

# Ensure only one run per branch/PR; cancel older in-progress if a new one starts
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  R-CMD-check:
    # OS × R version matrix
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest]
        r: [release] #, oldrel]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
          use-public-rspm: true

      - name: Cache R library
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.r }}-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-${{ matrix.r }}-
            ${{ runner.os }}-r-
            r-

      - name: Install package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # Option A: ensure rcmdcheck is installed
          extra-packages: |
            rcmdcheck


      - name: Run R CMD check
        uses: r-lib/actions/check-r-package@v2
        with:
          build_args: '--no-manual --as-cran'
