# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R-CMD-check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.3']

    steps:
      - uses: actions/checkout@v4
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
      
      - name: Install dependencies
        run: install.packages('rcmdcheck')
             install.packages('remotes')
             remotes::install_deps(dependencies = TRUE)  # ← Installs your package dependencies
             # other install commands here
      
      - name: Check
        uses: r-lib/actions/check-r-package@v2
